version: '3.8'

services:
  database:
    container_name: database_2048
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --log-bin-trust_function_creators=1
    environment:
      MYSQL_ROOT_PASSWORD: 2048
      MYSQL_DATABASE: 2048
      MYSQL_USER: 2048
      MYSQL_PASSWORD: 2048
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql